# Site settings

title: Al7075-T6 Particle Distribution Impact on Multiaxial Lives
header-img: img/rolls.jpg
email: pkern3@gatech.edu
description: "This site is a class project page for ME 8883 at Georgia Tech. Our specific project intends to investigate the impact on particle distributions in Al 7075-T6"
baseurl: "/ME8883"
url: "http://paulkern.github.io"
github_username:  paulkern
project_repository: ME8883

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
